apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-app-sa
  namespace: nodejs-app
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/managed-by: kubectl
automountServiceAccountToken: false
